# -*- coding: utf-8 -*-
"""
This code was auto-generated by Amua (https://github.com/zward/Amua)
Code generated: Sat May 31 23:05:33 JST 2025
Model name: S3_model_pancreatic_cancer
Model type: Markov Model
Simulation type: Monte Carlo
Created by: takuh
Created: Sat May 24 17:25:15 GMT+09:00 2025
Version created: 0.3.2
Modified by: takuh
Modified: Sun May 25 23:05:36 GMT+09:00 2025
Version modified: 0.3.2
"""
import math
import numpy as np

def returnIf(expr, a, b):
    if(expr): return(a)
    else: return(b)


